### ISSUE TITLE
Amazing Example - But what about cookies?

### ISSUE THREAD

**Issue by tomitrescak** [siim-m/next-fullstack-apollo-auth#6]
Hi, thanks for the example! 
I do not understand where you set the cookies though .. there is "setCookies" collection, but it is not used apart from pushing.

**Comment by siim-m** [comment]
Hi there!

It's been a while since I made this, so I had to refresh my memory. Looks like it's handled by the `apollo-server-plugin-http-headers` plugin in the background. A reference of the `setCookies` array is passed to the resolver. When Apollo Server sends a response to the client, it includes all the cookies that the resolver added.

https://www.npmjs.com/package/apollo-server-plugin-http-headers

**Comment by tomitrescak** [comment]
Thank you! Really helpful!
